### ISSUE TITLE
Riportare i riferimenti dei partecipanti

### ISSUE THREAD

**Issue by angelomaragna** [laravel-verona/annotations#1]
Comunicato il repository, permetterei a chi lo desiderati di mettere (o fornirci) i propri riferimenti da mettere negli argomenti

**Comment by billmn** [comment]
Esatto, chi desidera può inviare un **Pull Request** sul file desiderato e completare i propri riferimenti.

Altrimenti può anche comunicare i suoi riferimenti direttamente in questa issue.
