### ISSUE TITLE
Proposta sviluppo progetto

### ISSUE THREAD

**Issue by flavioski** [laravel-verona/annotations#10]
Ciao,

dove possiamo scrivere eventuali richieste di cosa vorremmo discutere?

@angelomaragna aveva chiesto se avevamo un piccolo progetto da sviluppare insieme, posso parlare qui?

**Comment by billmn** [comment]
Ciao @flavioski, sei nel posto giusto :+1: 

Per richieste relative ai Talk o per proporre un progetto su cui lavorare credo sia una buona idea aprire una issue in questo repository. In questo modo anche gli altri possono vedere le proposte esistenti e supportarle.

Grazie!

**Comment by flavioski** [comment]
Ottimo,

dunque il progetto che io ho in mente è un pò ambizioso, spero elegante e divertente..

volevo sviluppare un sistema di prenotazione (e pagamento) con rilevamento di prossimità.

Ambientazione
immaginate di andare con amici in un locale (o un pub, un ristorante, anche un negozio di abbigliamento, o il solito bar per l'aperitivo/spritz estivo ..) e l' ambiente e' pieno ma avete trovato un posto per sedervi.. ora incominciano i problemi:
1.nessuno arriva a prendere il vostro ordine
2.troppa gente = tanto casino e quindi non vi capite cosa ordinare e vi dovete urlare
3.non sapete nemmeno cosa ordinare perche' magari avete voglia di qualcosa di nuovo

insomma passa il tempo e attorno a voi tutti si divertono mentre voi siete ancora lì senza niente in mano..

Quello che vi propongo è un piccolo progetto: alla fine si tratta di realizzare un piccolo sito web dell' attività in questione, con tanto di menù e carrello per l' acquisto. Si pagherà con carta di credito (circuito PayPal o affini) e in meno di 10 min (spero) vi arriva tutto quanto!
Una persona in "cassa" non deve far altro che gestire la coda delle prenotazioni / acquisti e gestire conseguentemente gli ordini..
Col sistema di prossimità riconosce dove siete pertanto è impossibile che non arrivi quello che non è stato comprato.

Cosa ne pensate?

Flavio Pellizzer

**Comment by billmn** [comment]
Ciao Flavio e grazie per la proposta. 

Una domanda: come farebbe eventualmente il cameriere a sapere a quale tavolo portare l'ordine?

Potrebbe magari avere senso specificare in fase d'ordine il numero del tavolo?

**Comment by flavioski** [comment]
Ciao Davide,

un primo sviluppo sicuramente può essere pensato così. 
Forse mi sono espresso male, ma col termine  "prossimità" mi riferivo ai beacons 
http://www.wired.it/mobile/app/2014/09/26/come-i-beacon-rivoluzioneranno-musei-e-spazi-culturali/

L'articolo cita l'uso nei musei o spazi culturali..

**Comment by billmn** [comment]
Ah ok, ho capito. 

Comunque bene, questo sarà sicuramente un progetto da discutere insieme al prossimo meetup 👍

Grazie mille di nuovo per la proposta!
