### ISSUE TITLE
2016 - 2017

### ISSUE THREAD

**Issue by flavioski** [laravel-verona/annotations#13]
Ciao Laraveliani,

mi chiedevo se quest'anno si faranno i meetup.

Nel frattempo mi sto cimentando con la versione L 5.3.x
Abbiamo modo di creare un progetto insieme?
Io sono un po' indietro quindi accetto volentieri compitini da fare a casa.. sia come ripasso sia anche per accedere ad un livello piu' avanzato cosi' almeno potrei condividere le mie idee.

BG
Flavio

**Comment by billmn** [comment]
Ciao Flavio,
abbiamo subito una fase di stop ma cercheremo di riorganizzarci per riprendere i meetup.

L'idea non è quella di lasciare compiti per casa ma di trovarci insieme per condividere esperienze e conoscenze. Appena abbiamo novità non mancheremo di farti sapere :)

Ciao!
